name: Chromatic

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: ${{ secrets.CHROMATIC_PROJECT_TOKEN != '' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes

