name: Container Security

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/container-security.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.ts'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/container-security.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.ts'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
  merge_group:

jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t remotemaster-server-ui:ci .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: remotemaster-server-ui:ci
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          cache: true
      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@v0
        with:
          image: remotemaster-server-ui:ci
          format: cyclonedx-json
          output-file: sbom.cdx.json
          upload-artifact: true
          artifact-name: sbom-cyclonedx
