name: OSV Scanner

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run OSV Scanner
        uses: google/osv-scanner-action@v1
        with:
          scan-args: >-
            --lockfile=package-lock.json

